// wrapFortranBindings.cpp
// This file is generated by Shroud 0.14.0. Do not edit.

#include "FortranBindings.hpp"
#include "wrapFortranBindings.h"

// splicer begin CXX_definitions
// splicer end CXX_definitions

extern "C" {

// splicer begin C_definitions
// splicer end C_definitions

void FOR_solveDecompFloat(size_t frontBackPtr, const size_t fbLd,
    size_t leftRightPtr, const size_t lrLd, size_t topBottomPtr,
    const size_t tbLd, size_t fPtr, const size_t fStride, size_t xPtr,
    const size_t xStride, const size_t height, const size_t width,
    const size_t depth, size_t rowsXRowsPtr, const size_t rowsXRowsLd,
    size_t colsXColsPtr, const size_t colsXColsLd,
    size_t depthsXDepthsPtr, const size_t depthsXDepthsLd,
    size_t maxDimX3Ptr, const size_t maxDimX3Ld)
{
    // splicer begin function.solveDecompFloat
    solveDecompFloat(frontBackPtr, fbLd, leftRightPtr, lrLd,
        topBottomPtr, tbLd, fPtr, fStride, xPtr, xStride, height, width,
        depth, rowsXRowsPtr, rowsXRowsLd, colsXColsPtr, colsXColsLd,
        depthsXDepthsPtr, depthsXDepthsLd, maxDimX3Ptr, maxDimX3Ld);
    // splicer end function.solveDecompFloat
}

void FOR_solveDecompDouble(size_t frontBackPtr, const size_t fbLd,
    size_t leftRightPtr, const size_t lrLd, size_t topBottomPtr,
    const size_t tbLd, size_t fPtr, const size_t fStride, size_t xPtr,
    const size_t xStride, const size_t height, const size_t width,
    const size_t depth, size_t rowsXRowsPtr, const size_t rowsXRowsLd,
    size_t colsXColsPtr, const size_t colsXColsLd,
    size_t depthsXDepthsPtr, const size_t depthsXDepthsLd,
    size_t maxDimX3Ptr, const size_t maxDimX3Ld)
{
    // splicer begin function.solveDecompDouble
    solveDecompDouble(frontBackPtr, fbLd, leftRightPtr, lrLd,
        topBottomPtr, tbLd, fPtr, fStride, xPtr, xStride, height, width,
        depth, rowsXRowsPtr, rowsXRowsLd, colsXColsPtr, colsXColsLd,
        depthsXDepthsPtr, depthsXDepthsLd, maxDimX3Ptr, maxDimX3Ld);
    // splicer end function.solveDecompDouble
}

void FOR_solveBiCGSTAB_float(size_t APtr, const size_t aLd,
    size_t indsPtrInt32_t, const size_t indsStride,
    const size_t numInds, size_t bPtr, const size_t bStride,
    const size_t bSize, size_t prealocatedSizeX7Ptr,
    const size_t prealocatedLd, size_t maxIterations, float tolerance)
{
    // splicer begin function.solveBiCGSTAB_float
    solveBiCGSTAB<float>(APtr, aLd, indsPtrInt32_t, indsStride, numInds,
        bPtr, bStride, bSize, prealocatedSizeX7Ptr, prealocatedLd,
        maxIterations, tolerance);
    // splicer end function.solveBiCGSTAB_float
}

void FOR_solveBiCGSTAB_double(size_t APtr, const size_t aLd,
    size_t indsPtrInt32_t, const size_t indsStride,
    const size_t numInds, size_t bPtr, const size_t bStride,
    const size_t bSize, size_t prealocatedSizeX7Ptr,
    const size_t prealocatedLd, size_t maxIterations, double tolerance)
{
    // splicer begin function.solveBiCGSTAB_double
    solveBiCGSTAB<double>(APtr, aLd, indsPtrInt32_t, indsStride,
        numInds, bPtr, bStride, bSize, prealocatedSizeX7Ptr,
        prealocatedLd, maxIterations, tolerance);
    // splicer end function.solveBiCGSTAB_double
}

}  // extern "C"
