// wrapFortranBindings.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapFortranBindings.h
 * \brief Shroud generated wrapper for FortranBindings library
 */
// For C users and C++ implementation

#ifndef WRAPFORTRANBINDINGS_H
#define WRAPFORTRANBINDINGS_H

#ifdef __cplusplus
#include <cstddef>
#else
#include <stddef.h>
#endif
#include "typesFortranBindings.h"

// splicer begin CXX_declarations
// splicer end CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin C_declarations
// splicer end C_declarations

void FOR_solveDecompFloat(size_t frontBackPtr, const size_t fbLd,
    size_t leftRightPtr, const size_t lrLd, size_t topBottomPtr,
    const size_t tbLd, size_t fPtr, const size_t fStride, size_t xPtr,
    const size_t xStride, const size_t height, const size_t width,
    const size_t depth, size_t rowsXRowsPtr, const size_t rowsXRowsLd,
    size_t colsXColsPtr, const size_t colsXColsLd,
    size_t depthsXDepthsPtr, const size_t depthsXDepthsLd,
    size_t maxDimX3Ptr, const size_t maxDimX3Ld);

void FOR_solveDecompDouble(size_t frontBackPtr, const size_t fbLd,
    size_t leftRightPtr, const size_t lrLd, size_t topBottomPtr,
    const size_t tbLd, size_t fPtr, const size_t fStride, size_t xPtr,
    const size_t xStride, const size_t height, const size_t width,
    const size_t depth, size_t rowsXRowsPtr, const size_t rowsXRowsLd,
    size_t colsXColsPtr, const size_t colsXColsLd,
    size_t depthsXDepthsPtr, const size_t depthsXDepthsLd,
    size_t maxDimX3Ptr, const size_t maxDimX3Ld);

void FOR_solveBiCGSTAB_float(size_t APtr, const size_t aLd,
    size_t indsPtrInt32_t, const size_t indsStride,
    const size_t numInds, size_t bPtr, const size_t bStride,
    const size_t bSize, size_t prealocatedSizeX7Ptr,
    const size_t prealocatedLd, size_t maxIterations, float tolerance);

void FOR_solveBiCGSTAB_double(size_t APtr, const size_t aLd,
    size_t indsPtrInt32_t, const size_t indsStride,
    const size_t numInds, size_t bPtr, const size_t bStride,
    const size_t bSize, size_t prealocatedSizeX7Ptr,
    const size_t prealocatedLd, size_t maxIterations, double tolerance);

#ifdef __cplusplus
}
#endif

#endif  // WRAPFORTRANBINDINGS_H
