! wrapffortranbindings.f
! This file is generated by Shroud 0.14.0. Do not edit.
!>
!! \file wrapffortranbindings.f
!! \brief Shroud generated wrapper for FortranBindings library
!<
! splicer begin file_top
! splicer end file_top
module fortranbindings_mod
    ! splicer begin module_use
    ! splicer end module_use
    implicit none

    ! splicer begin module_top
    ! splicer end module_top

    interface

        subroutine c_solve_decomp_float(frontBackPtr, fbLd, &
                leftRightPtr, lrLd, topBottomPtr, tbLd, fPtr, fStride, &
                xPtr, xStride, height, width, depth, rowsXRowsPtr, &
                rowsXRowsLd, colsXColsPtr, colsXColsLd, &
                depthsXDepthsPtr, depthsXDepthsLd, maxDimX3Ptr, &
                maxDimX3Ld) &
                bind(C, name="FOR_solveDecomp_float")
            use iso_c_binding, only : C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: frontBackPtr
            integer(C_SIZE_T), value, intent(IN) :: fbLd
            integer(C_SIZE_T), value, intent(IN) :: leftRightPtr
            integer(C_SIZE_T), value, intent(IN) :: lrLd
            integer(C_SIZE_T), value, intent(IN) :: topBottomPtr
            integer(C_SIZE_T), value, intent(IN) :: tbLd
            integer(C_SIZE_T), value, intent(IN) :: fPtr
            integer(C_SIZE_T), value, intent(IN) :: fStride
            integer(C_SIZE_T), value, intent(IN) :: xPtr
            integer(C_SIZE_T), value, intent(IN) :: xStride
            integer(C_SIZE_T), value, intent(IN) :: height
            integer(C_SIZE_T), value, intent(IN) :: width
            integer(C_SIZE_T), value, intent(IN) :: depth
            integer(C_SIZE_T), value, intent(IN) :: rowsXRowsPtr
            integer(C_SIZE_T), value, intent(IN) :: rowsXRowsLd
            integer(C_SIZE_T), value, intent(IN) :: colsXColsPtr
            integer(C_SIZE_T), value, intent(IN) :: colsXColsLd
            integer(C_SIZE_T), value, intent(IN) :: depthsXDepthsPtr
            integer(C_SIZE_T), value, intent(IN) :: depthsXDepthsLd
            integer(C_SIZE_T), value, intent(IN) :: maxDimX3Ptr
            integer(C_SIZE_T), value, intent(IN) :: maxDimX3Ld
        end subroutine c_solve_decomp_float

        subroutine c_solve_decomp_double(frontBackPtr, fbLd, &
                leftRightPtr, lrLd, topBottomPtr, tbLd, fPtr, fStride, &
                xPtr, xStride, height, width, depth, rowsXRowsPtr, &
                rowsXRowsLd, colsXColsPtr, colsXColsLd, &
                depthsXDepthsPtr, depthsXDepthsLd, maxDimX3Ptr, &
                maxDimX3Ld) &
                bind(C, name="FOR_solveDecomp_double")
            use iso_c_binding, only : C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: frontBackPtr
            integer(C_SIZE_T), value, intent(IN) :: fbLd
            integer(C_SIZE_T), value, intent(IN) :: leftRightPtr
            integer(C_SIZE_T), value, intent(IN) :: lrLd
            integer(C_SIZE_T), value, intent(IN) :: topBottomPtr
            integer(C_SIZE_T), value, intent(IN) :: tbLd
            integer(C_SIZE_T), value, intent(IN) :: fPtr
            integer(C_SIZE_T), value, intent(IN) :: fStride
            integer(C_SIZE_T), value, intent(IN) :: xPtr
            integer(C_SIZE_T), value, intent(IN) :: xStride
            integer(C_SIZE_T), value, intent(IN) :: height
            integer(C_SIZE_T), value, intent(IN) :: width
            integer(C_SIZE_T), value, intent(IN) :: depth
            integer(C_SIZE_T), value, intent(IN) :: rowsXRowsPtr
            integer(C_SIZE_T), value, intent(IN) :: rowsXRowsLd
            integer(C_SIZE_T), value, intent(IN) :: colsXColsPtr
            integer(C_SIZE_T), value, intent(IN) :: colsXColsLd
            integer(C_SIZE_T), value, intent(IN) :: depthsXDepthsPtr
            integer(C_SIZE_T), value, intent(IN) :: depthsXDepthsLd
            integer(C_SIZE_T), value, intent(IN) :: maxDimX3Ptr
            integer(C_SIZE_T), value, intent(IN) :: maxDimX3Ld
        end subroutine c_solve_decomp_double

        subroutine c_solve_bi_cgstab_float(APtr, aLd, indsPtrInt32_t, &
                indsStride, numInds, bPtr, bStride, bSize, &
                prealocatedSizeX7Ptr, prealocatedLd, maxIterations, &
                tolerance) &
                bind(C, name="FOR_solveBiCGSTAB_float")
            use iso_c_binding, only : C_FLOAT, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: APtr
            integer(C_SIZE_T), value, intent(IN) :: aLd
            integer(C_SIZE_T), value, intent(IN) :: indsPtrInt32_t
            integer(C_SIZE_T), value, intent(IN) :: indsStride
            integer(C_SIZE_T), value, intent(IN) :: numInds
            integer(C_SIZE_T), value, intent(IN) :: bPtr
            integer(C_SIZE_T), value, intent(IN) :: bStride
            integer(C_SIZE_T), value, intent(IN) :: bSize
            integer(C_SIZE_T), value, intent(IN) :: prealocatedSizeX7Ptr
            integer(C_SIZE_T), value, intent(IN) :: prealocatedLd
            integer(C_SIZE_T), value, intent(IN) :: maxIterations
            real(C_FLOAT), value, intent(IN) :: tolerance
        end subroutine c_solve_bi_cgstab_float

        subroutine c_solve_bi_cgstab_double(APtr, aLd, indsPtrInt32_t, &
                indsStride, numInds, bPtr, bStride, bSize, &
                prealocatedSizeX7Ptr, prealocatedLd, maxIterations, &
                tolerance) &
                bind(C, name="FOR_solveBiCGSTAB_double")
            use iso_c_binding, only : C_DOUBLE, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: APtr
            integer(C_SIZE_T), value, intent(IN) :: aLd
            integer(C_SIZE_T), value, intent(IN) :: indsPtrInt32_t
            integer(C_SIZE_T), value, intent(IN) :: indsStride
            integer(C_SIZE_T), value, intent(IN) :: numInds
            integer(C_SIZE_T), value, intent(IN) :: bPtr
            integer(C_SIZE_T), value, intent(IN) :: bStride
            integer(C_SIZE_T), value, intent(IN) :: bSize
            integer(C_SIZE_T), value, intent(IN) :: prealocatedSizeX7Ptr
            integer(C_SIZE_T), value, intent(IN) :: prealocatedLd
            integer(C_SIZE_T), value, intent(IN) :: maxIterations
            real(C_DOUBLE), value, intent(IN) :: tolerance
        end subroutine c_solve_bi_cgstab_double
    end interface

    interface solve_bi_cgstab
        module procedure solve_bi_cgstab_float
        module procedure solve_bi_cgstab_double
    end interface solve_bi_cgstab

    interface solve_decomp
        module procedure solve_decomp_float
        module procedure solve_decomp_double
    end interface solve_decomp

    ! splicer begin additional_declarations
    ! splicer end additional_declarations

contains

    subroutine solve_decomp_float(frontBackPtr, fbLd, leftRightPtr, &
            lrLd, topBottomPtr, tbLd, fPtr, fStride, xPtr, xStride, &
            height, width, depth, rowsXRowsPtr, rowsXRowsLd, &
            colsXColsPtr, colsXColsLd, depthsXDepthsPtr, &
            depthsXDepthsLd, maxDimX3Ptr, maxDimX3Ld)
        use iso_c_binding, only : C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: frontBackPtr
        integer(C_SIZE_T), value, intent(IN) :: fbLd
        integer(C_SIZE_T), value, intent(IN) :: leftRightPtr
        integer(C_SIZE_T), value, intent(IN) :: lrLd
        integer(C_SIZE_T), value, intent(IN) :: topBottomPtr
        integer(C_SIZE_T), value, intent(IN) :: tbLd
        integer(C_SIZE_T), value, intent(IN) :: fPtr
        integer(C_SIZE_T), value, intent(IN) :: fStride
        integer(C_SIZE_T), value, intent(IN) :: xPtr
        integer(C_SIZE_T), value, intent(IN) :: xStride
        integer(C_SIZE_T), value, intent(IN) :: height
        integer(C_SIZE_T), value, intent(IN) :: width
        integer(C_SIZE_T), value, intent(IN) :: depth
        integer(C_SIZE_T), value, intent(IN) :: rowsXRowsPtr
        integer(C_SIZE_T), value, intent(IN) :: rowsXRowsLd
        integer(C_SIZE_T), value, intent(IN) :: colsXColsPtr
        integer(C_SIZE_T), value, intent(IN) :: colsXColsLd
        integer(C_SIZE_T), value, intent(IN) :: depthsXDepthsPtr
        integer(C_SIZE_T), value, intent(IN) :: depthsXDepthsLd
        integer(C_SIZE_T), value, intent(IN) :: maxDimX3Ptr
        integer(C_SIZE_T), value, intent(IN) :: maxDimX3Ld
        ! splicer begin function.solve_decomp_float
        call c_solve_decomp_float(frontBackPtr, fbLd, leftRightPtr, &
            lrLd, topBottomPtr, tbLd, fPtr, fStride, xPtr, xStride, &
            height, width, depth, rowsXRowsPtr, rowsXRowsLd, &
            colsXColsPtr, colsXColsLd, depthsXDepthsPtr, &
            depthsXDepthsLd, maxDimX3Ptr, maxDimX3Ld)
        ! splicer end function.solve_decomp_float
    end subroutine solve_decomp_float

    subroutine solve_decomp_double(frontBackPtr, fbLd, leftRightPtr, &
            lrLd, topBottomPtr, tbLd, fPtr, fStride, xPtr, xStride, &
            height, width, depth, rowsXRowsPtr, rowsXRowsLd, &
            colsXColsPtr, colsXColsLd, depthsXDepthsPtr, &
            depthsXDepthsLd, maxDimX3Ptr, maxDimX3Ld)
        use iso_c_binding, only : C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: frontBackPtr
        integer(C_SIZE_T), value, intent(IN) :: fbLd
        integer(C_SIZE_T), value, intent(IN) :: leftRightPtr
        integer(C_SIZE_T), value, intent(IN) :: lrLd
        integer(C_SIZE_T), value, intent(IN) :: topBottomPtr
        integer(C_SIZE_T), value, intent(IN) :: tbLd
        integer(C_SIZE_T), value, intent(IN) :: fPtr
        integer(C_SIZE_T), value, intent(IN) :: fStride
        integer(C_SIZE_T), value, intent(IN) :: xPtr
        integer(C_SIZE_T), value, intent(IN) :: xStride
        integer(C_SIZE_T), value, intent(IN) :: height
        integer(C_SIZE_T), value, intent(IN) :: width
        integer(C_SIZE_T), value, intent(IN) :: depth
        integer(C_SIZE_T), value, intent(IN) :: rowsXRowsPtr
        integer(C_SIZE_T), value, intent(IN) :: rowsXRowsLd
        integer(C_SIZE_T), value, intent(IN) :: colsXColsPtr
        integer(C_SIZE_T), value, intent(IN) :: colsXColsLd
        integer(C_SIZE_T), value, intent(IN) :: depthsXDepthsPtr
        integer(C_SIZE_T), value, intent(IN) :: depthsXDepthsLd
        integer(C_SIZE_T), value, intent(IN) :: maxDimX3Ptr
        integer(C_SIZE_T), value, intent(IN) :: maxDimX3Ld
        ! splicer begin function.solve_decomp_double
        call c_solve_decomp_double(frontBackPtr, fbLd, leftRightPtr, &
            lrLd, topBottomPtr, tbLd, fPtr, fStride, xPtr, xStride, &
            height, width, depth, rowsXRowsPtr, rowsXRowsLd, &
            colsXColsPtr, colsXColsLd, depthsXDepthsPtr, &
            depthsXDepthsLd, maxDimX3Ptr, maxDimX3Ld)
        ! splicer end function.solve_decomp_double
    end subroutine solve_decomp_double

    subroutine solve_bi_cgstab_float(APtr, aLd, indsPtrInt32_t, &
            indsStride, numInds, bPtr, bStride, bSize, &
            prealocatedSizeX7Ptr, prealocatedLd, maxIterations, &
            tolerance)
        use iso_c_binding, only : C_FLOAT, C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: APtr
        integer(C_SIZE_T), value, intent(IN) :: aLd
        integer(C_SIZE_T), value, intent(IN) :: indsPtrInt32_t
        integer(C_SIZE_T), value, intent(IN) :: indsStride
        integer(C_SIZE_T), value, intent(IN) :: numInds
        integer(C_SIZE_T), value, intent(IN) :: bPtr
        integer(C_SIZE_T), value, intent(IN) :: bStride
        integer(C_SIZE_T), value, intent(IN) :: bSize
        integer(C_SIZE_T), value, intent(IN) :: prealocatedSizeX7Ptr
        integer(C_SIZE_T), value, intent(IN) :: prealocatedLd
        integer(C_SIZE_T), value, intent(IN) :: maxIterations
        real(C_FLOAT), value, intent(IN) :: tolerance
        ! splicer begin function.solve_bi_cgstab_float
        call c_solve_bi_cgstab_float(APtr, aLd, indsPtrInt32_t, &
            indsStride, numInds, bPtr, bStride, bSize, &
            prealocatedSizeX7Ptr, prealocatedLd, maxIterations, &
            tolerance)
        ! splicer end function.solve_bi_cgstab_float
    end subroutine solve_bi_cgstab_float

    subroutine solve_bi_cgstab_double(APtr, aLd, indsPtrInt32_t, &
            indsStride, numInds, bPtr, bStride, bSize, &
            prealocatedSizeX7Ptr, prealocatedLd, maxIterations, &
            tolerance)
        use iso_c_binding, only : C_DOUBLE, C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: APtr
        integer(C_SIZE_T), value, intent(IN) :: aLd
        integer(C_SIZE_T), value, intent(IN) :: indsPtrInt32_t
        integer(C_SIZE_T), value, intent(IN) :: indsStride
        integer(C_SIZE_T), value, intent(IN) :: numInds
        integer(C_SIZE_T), value, intent(IN) :: bPtr
        integer(C_SIZE_T), value, intent(IN) :: bStride
        integer(C_SIZE_T), value, intent(IN) :: bSize
        integer(C_SIZE_T), value, intent(IN) :: prealocatedSizeX7Ptr
        integer(C_SIZE_T), value, intent(IN) :: prealocatedLd
        integer(C_SIZE_T), value, intent(IN) :: maxIterations
        real(C_DOUBLE), value, intent(IN) :: tolerance
        ! splicer begin function.solve_bi_cgstab_double
        call c_solve_bi_cgstab_double(APtr, aLd, indsPtrInt32_t, &
            indsStride, numInds, bPtr, bStride, bSize, &
            prealocatedSizeX7Ptr, prealocatedLd, maxIterations, &
            tolerance)
        ! splicer end function.solve_bi_cgstab_double
    end subroutine solve_bi_cgstab_double

    ! splicer begin additional_functions
    ! splicer end additional_functions

end module fortranbindings_mod
