! wrapffortranbindings.f
! This file is generated by Shroud 0.14.0. Do not edit.
!>
!! \file wrapffortranbindings.f
!! \brief Shroud generated wrapper for FortranBindings library
!<
! splicer begin file_top
! splicer end file_top
module fortranbindings_mod
    ! splicer begin module_use
    ! splicer end module_use
    implicit none

    ! splicer begin module_top
    ! splicer end module_top

    ! splicer begin additional_declarations
    ! splicer end additional_declarations

contains

    ! splicer begin additional_functions
    ! splicer end additional_functions

end module fortranbindings_mod
