// wrapFortranBindings.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapFortranBindings.h
 * \brief Shroud generated wrapper for FortranBindings library
 */
// For C users and C++ implementation

#ifndef WRAPFORTRANBINDINGS_H
#define WRAPFORTRANBINDINGS_H

#ifdef __cplusplus
#include <cstddef>
#include <cstdint>
#else
#include <stddef.h>
#include <stdint.h>
#endif
#include "typesFortranBindings.h"

// splicer begin CXX_declarations
// splicer end CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin C_declarations
// splicer end C_declarations

void FOR_solveDecomp_float(float *frontBack, const size_t fbLd,
    float *leftRight, const size_t lrLd, float *topBottom,
    const size_t tbLd, float *f, const size_t fStride, float *x,
    const size_t xStride, const size_t height, const size_t width,
    const size_t depth, float *rowsXRows, const size_t rowsXRowsLd,
    float *colsXCols, const size_t colsXColsLd, float *depthsXDepths,
    const size_t depthsXDepthsLd, float *maxDimX3,
    const size_t maxDimX3Ld);

void FOR_solveDecomp_double(double *frontBack, const size_t fbLd,
    double *leftRight, const size_t lrLd, double *topBottom,
    const size_t tbLd, double *f, const size_t fStride, double *x,
    const size_t xStride, const size_t height, const size_t width,
    const size_t depth, double *rowsXRows, const size_t rowsXRowsLd,
    double *colsXCols, const size_t colsXColsLd, double *depthsXDepths,
    const size_t depthsXDepthsLd, double *maxDimX3,
    const size_t maxDimX3Ld);

void FOR_solveBiCGSTAB_float(float *A, const size_t aLd, int32_t *inds,
    const size_t indsStride, const size_t numInds, float *b,
    const size_t bSize, float *prealocatedSizeX7,
    const size_t prealocatedLd, size_t maxIterations, float tolerance);

void FOR_solveBiCGSTAB_double(double *A, const size_t aLd,
    int32_t *inds, const size_t indsStride, const size_t numInds,
    double *b, const size_t bSize, double *prealocatedSizeX7,
    const size_t prealocatedLd, size_t maxIterations, double tolerance);

#ifdef __cplusplus
}
#endif

#endif  // WRAPFORTRANBINDINGS_H
